name: "To Lowercase"
description: |
  Lowercase output
inputs:
  project:
    description: "project name"
    required: false
    default: ""
outputs:
  project:
    description: lower case project
    value: ${{ steps.project.outputs.lowercase }}
  repository:
    description: lower case repository
    value: ${{ steps.repository.outputs.lowercase }}
runs:
  using: "composite"
  steps:
    - id: repository
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ github.repository }}

    - id: project
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ inputs.project }}
