name: "To Lowercase"
description: Lowercase output
inputs:
  project:
    description: "project name"
    required: false
    default: ""
outputs:
  project:
    description: "project name in lowercase"
    value: ${{ steps.project.outputs.lowercase }}
  repository:
    description: "repository name in lowercase"
    value: ${{ steps.repository.outputs.lowercase }}
runs:
  using: "composite"
  steps:
    - name: repository lowercase
      run: echo "lowercase=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      id: repository
      shell: bash

    - name: project lowercase
      run: echo "lowercase=$(echo '${{ inputs.project }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      id: project
      shell: bash
