apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore60-healthcheck
spec:
  selector:
    matchLabels:
      app: aspnetcore60-healthcheck
  template:
    metadata:
      labels:
        app: aspnetcore60-healthcheck
    spec:
      containers:
        - name: aspnetcore60-healthcheck
          image: guitarrapc/csharp-lab:latest-grpc-aspnetcore60.healthchecksupport
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - name: grpc
              containerPort: 80
          readinessProbe:
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=localhost:80",
                  "-connect-timeout=1s",
                  "-rpc-timeout=2s",
                ]
            initialDelaySeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=localhost:80",
                  "-connect-timeout=1s",
                  "-rpc-timeout=2s",
                ]
            initialDelaySeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcore60-healthcheck
spec:
  selector:
    app: aspnetcore60-healthcheck
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: grpc
