apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore60-healthcheck
spec:
  selector:
    matchLabels:
      app: aspnetcore60-healthcheck
  template:
    metadata:
      labels:
        app: aspnetcore60-healthcheck
    spec:
      containers:
        - name: aspnetcore60-healthcheck
          image: guitarrapc/csharp-lab:latest-grpc-aspnetcore60.healthchecksupport
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - name: grpc
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcore60-healthcheck
spec:
  selector:
    app: aspnetcore60-healthcheck
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: grpc
