name: "Problem Matcher for dotnet-format"

description: "Sets up a problem matcher for dotnet-format that's used to create annotations for violations"

author: "xt0rted"

branding:
  icon: "command"
  color: "green"

inputs:
  action:
    description: "The action to take on the problem matcher (add or remove)"
    required: false
    default: add

runs:
  using: "node16"
  main: "dist/index.js"
