name: (R) Build Dotnet

on:
  workflow_call:
    inputs:
      build-config:
        description: 'Build Configuration (Debug or Release)'
        required: true
        default: 'Release'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          restore-wasm-workload: true
          dotnet-version: |
            6.0.x
            7.0.x
      - name: dotnet build
        run: dotnet build -c ${{ inputs.build-config }}
      - name: dotnet test
        run: dotnet test -c ${{ inputs.build-config }} --logger GitHubActions
      - name: dotnet publish
        run: dotnet publish -c ${{ inputs.build-config }}
