name: Benchmarker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday.
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_CONFIG: Release
  SKIP_CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz # Q4 2013, too old and slow to benchmark. Skip benchmark if detected.

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: Logger.Benchmark
            csproj: ./src/Logger/Logger.Benchmark/Logger.Benchmark.csproj
          - project: Logic.Benchmark
            csproj: ./src/Logic/Logic.Benchmark/Logic.Benchmark.csproj
          - project: MemoryLeak.Benchmark
            csproj: ./src/MemoryLeak/MemoryLeak.Benchmark/MemoryLeak.Benchmark.csproj
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: CPU Detection
        id: cpu
        run: |
          cpu=$(less /proc/cpuinfo | grep -m 1 'model name' | cut -f 2 -d ":")
          echo "name=${cpu:1}" | tee -a "${GITHUB_OUTPUT}"
          echo "execute=$([[ "${cpu:1}" != "${{ env.SKIP_CPU }}" ]] && echo 1 || echo 0)" | tee -a "${GITHUB_OUTPUT}"
      - uses: actions/checkout@v3
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          restore-wasm-workload: true
          dotnet-version: |
            6.0.x
            7.0.x
      - name: dotnet build
        run: dotnet build ${{ matrix.csproj }} -c ${{ env.BUILD_CONFIG }}
      - name: Run benchmark
        if: ${{ steps.cpu.outputs.execute == 1 }}
        run: |
          dotnet run --project ${{ matrix.csproj }} -c ${{ env.BUILD_CONFIG }}
          while read -r file; do
            cat "$file" >> "$GITHUB_STEP_SUMMARY"
          done <<< "$(find "./BenchmarkDotNet.Artifacts/results" -name "*.md" -type f)"
      - name: Skip benchmark
        if: ${{ steps.cpu.outputs.execute == 0 }}
        run: mkdir -p ./BenchmarkDotNet.Artifacts/results/ && echo "" >> ./BenchmarkDotNet.Artifacts/results/dummy.md # dummy file to upload
      - name: Upload summary
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.project }}"
          path: ./BenchmarkDotNet.Artifacts/results/*.md
          retention-days: 1

  # run on push and others
  update-doc:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [benchmark]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }} # checkout PR HEAD commit instead of merge commit

      - name: Download Logger.Benchmark
        uses: actions/download-artifact@v3
        with:
          name: Logger.Benchmark
          path: ./BenchmarkDotNet.Artifacts/Logger.Benchmark/
      # find *.md files exclude dummy.md and cat all files.
      # -exec cat + is not stable order.
      - name: Write summary to README.md
        run: find "./BenchmarkDotNet.Artifacts/Logger.Benchmark/" ! -name "dummy.md" -name "*.md" -type f | xargs -I {i} sh -c 'echo "# $(basename {i})\n"; cat {i}' > ./src/Logger/Logger.Benchmark//README.md

      - name: Download Logic.Benchmark
        uses: actions/download-artifact@v3
        with:
          name: Logic.Benchmark
          path: ./BenchmarkDotNet.Artifacts/Logic.Benchmark/
      - name: Write summary to README.md
        run: find "./BenchmarkDotNet.Artifacts/Logic.Benchmark/" ! -name "dummy.md" -name "*.md" -type f | xargs -I {i} sh -c 'echo "# $(basename {i})\n"; cat {i}' > ./src/Logic/Logic.Benchmark/README.md

      - name: Download MemoryLeak.Benchmark
        uses: actions/download-artifact@v3
        with:
          name: MemoryLeak.Benchmark
          path: ./BenchmarkDotNet.Artifacts/MemoryLeak.Benchmark/
      - name: Write summary to README.md
        run: find "./BenchmarkDotNet.Artifacts/MemoryLeak.Benchmark/" ! -name "dummy.md" -name "*.md" -type f | xargs -I {i} sh -c 'echo "# $(basename {i})\n"; cat {i}' >./src/MemoryLeak/MemoryLeak.Benchmark//README.md

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "[auto commit] Benchmark result updated."
