name: Benchmarker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday.
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_CONFIG: Release

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: Logger.Benchmark
            csproj: ./src/Logger/Logger.Benchmark/Logger.Benchmark.csproj
          - project: Logic.Benchmark
            csproj: ./src/Logic/Logic.Benchmark/Logic.Benchmark.csproj
          - project: MemoryLeak.Benchmark
            csproj: ./src/MemoryLeak/MemoryLeak.Benchmark/MemoryLeak.Benchmark.csproj
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          restore-wasm-workload: true
          dotnet-version: |
            6.0.x
            7.0.x
      - name: dotnet build
        run: dotnet build ${{ matrix.csproj }} -c ${{ env.BUILD_CONFIG }}
      - name: Run benchmark
        run: |
          dotnet run --project ${{ matrix.csproj }} -c ${{ env.BUILD_CONFIG }}
          while read -r file; do
            cat "$file" >> "$GITHUB_STEP_SUMMARY"
          done <<< "$(find "./BenchmarkDotNet.Artifacts/results" -name "*.md" -type f)"
      - name: Upload summary
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.project }}"
          path: ./BenchmarkDotNet.Artifacts/results/*.md
          retention-days: 1

  # only run on PR, not allowed to direct push main.
  update-doc:
    if: ${{ github.event_name == 'pull_request' }}
    needs: [benchmark]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }} # checkout PR HEAD commit instead of merge commit

      - name: Download Logger.Benchmark
        uses: actions/download-artifact@v3
        with:
          name: Logger.Benchmark
          path: ./BenchmarkDotNet.Artifacts/Logger.Benchmark/
      # -exec cat + is not stable order.
      - name: Write summary to README.md
        run: find "./BenchmarkDotNet.Artifacts/Logger.Benchmark/" -name "*.md" -type f | xargs -I {i} sh -c 'echo "# $(basename {i})\n"; cat {i}' > ./src/Logger/Logger.Benchmark//README.md

      - name: Download Logic.Benchmark
        uses: actions/download-artifact@v3
        with:
          name: Logic.Benchmark
          path: ./BenchmarkDotNet.Artifacts/Logic.Benchmark/
      - name: Write summary to README.md
        run: find "./BenchmarkDotNet.Artifacts/Logic.Benchmark/" -name "*.md" -type f | xargs -I {i} sh -c 'echo "# $(basename {i})\n"; cat {i}' > ./src/Logic/Logic.Benchmark/README.md

      - name: Download MemoryLeak.Benchmark
        uses: actions/download-artifact@v3
        with:
          name: MemoryLeak.Benchmark
          path: ./BenchmarkDotNet.Artifacts/MemoryLeak.Benchmark/
      - name: Write summary to README.md
        run: find "./BenchmarkDotNet.Artifacts/MemoryLeak.Benchmark/" -name "*.md" -type f | xargs -I {i} sh -c 'echo "# $(basename {i})\n"; cat {i}' >./src/MemoryLeak/MemoryLeak.Benchmark//README.md

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "[auto commit] Benchmark result updated."
