name: Benchmarker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday.
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_CONFIG: Release

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: Logger.Benchmark
            csproj: ./src/Logger/Logger.Benchmark/Logger.Benchmark.csproj
          - project: Logger.Benchmark
            csproj: ./src/Logger/Logger.Benchmark/Logger.Benchmark.csproj
          - project: MemoryLeak.Benchmark
            csproj: ./src/Logic/MemoryLeak.Benchmark/MemoryLeak.Benchmark.csproj
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          restore-wasm-workload: true
          dotnet-version: |
            6.0.x
            7.0.x
      - name: dotnet build
        run: dotnet build ${{ matrix.csproj }} -c ${{ env.BUILD_CONFIG }}
      - name: Run benchmark
        run: |
          dotnet run --project ${{ matrix.csproj }} -c ${{ env.BUILD_CONFIG }}
          for file in $(find "./BenchmarkDotNet.Artifacts/results" -name "*.md" -type f); do
            cat $file >> "$GITHUB_STEP_SUMMARY"
          done
