name: Benchmarker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday.
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_CONFIG: Release
  SKIP_CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz # Q4 2016, too slow to benchmark. Skip benchmark if detected.

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: Logger.Benchmark
            csproj: Logger.Benchmark.csproj
            path: src/Logger/Logger.Benchmark
          - project: Logic.Benchmark
            csproj: Logic.Benchmark.csproj
            path: src/Logic/Logic.Benchmark
          - project: MemoryLeak.Benchmark
            csproj: MemoryLeak.Benchmark.csproj
            path: src/MemoryLeak/MemoryLeak.Benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: CPU Detection
        id: cpu
        run: |
          cpu=$(less /proc/cpuinfo | grep -m 1 'model name' | cut -f 2 -d ":")
          echo "name=${cpu:1}" | tee -a "${GITHUB_OUTPUT}"
          echo "execute=$([[ "${cpu:1}" != "${{ env.SKIP_CPU }}" ]] && echo 1 || echo 0)" | tee -a "${GITHUB_OUTPUT}"
      - uses: actions/checkout@v3
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          restore-wasm-workload: true
          dotnet-version: |
            6.0.x
            7.0.x
      - name: dotnet build
        run: dotnet build ./${{ matrix.path}}/${{ matrix.csproj }} -c ${{ env.BUILD_CONFIG }}
      - name: Run benchmark
        if: ${{ steps.cpu.outputs.execute == 1 }}
        run: |
          dotnet run --project ./${{ matrix.path}}/${{ matrix.csproj }} -c ${{ env.BUILD_CONFIG }}
          mkdir -p ./BenchmarkDotNet.Artifacts/outputs/${{ matrix.path}}
          while read -r file; do
            cat "$file" >> "$GITHUB_STEP_SUMMARY"
            bench_name=$(echo "$file" | cut -d '/' -f 4 | cut -d '.' -f 2 | cut -d '-' -f 1)
            cat "$file" > ./BenchmarkDotNet.Artifacts/outputs/${{ matrix.path }}/${bench_name}.md
            echo "${{ matrix.path }}/README.${bench_name}.md" > ./BenchmarkDotNet.Artifacts/outputs/${{ matrix.path }}/${bench_name}.md.path
          done <<< "$(find "./BenchmarkDotNet.Artifacts/results" -name "*.md" -type f)"
      - name: Skip benchmark
        if: ${{ steps.cpu.outputs.execute == 0 }}
        run: mkdir -p ./BenchmarkDotNet.Artifacts/outputs/ && echo "" >> ./BenchmarkDotNet.Artifacts/outputs/dummy.md # dummy file to upload
      - name: Upload summary
        uses: actions/upload-artifact@v2
        with:
          name: "benchmarks"
          path: ./BenchmarkDotNet.Artifacts/outputs/
          retention-days: 1

  # run on pull_request only
  update-doc:
    if: ${{ github.event_name == 'pull_request' }}
    needs: [benchmark]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || '' }} # checkout PR HEAD branch instead of merge commit. use ref instead of sha to avoid detached HEAD and re-run.

      - name: Download Logger.Benchmark
        uses: actions/download-artifact@v3
        with:
          path: ./BenchmarkDotNet.Artifacts/outputs/

      - name: Write summary to README.md
        run: |
          while read -r file; do
            path=$(head -n 1 "${file}.path")
            cat "$file" > $path
          done <<< $(find "./BenchmarkDotNet.Artifacts/outputs/" ! -name "dummy.md" -name "*.md" -type f)

      # find *.md files exclude dummy.md and cat all files.
      # -exec cat + is not stable order.
      # write to README.md if *.md files are found. ignore if only dummy.md found.
      - name: Write summary to README.md
        run: |
          files=$(find "./BenchmarkDotNet.Artifacts/Logger.Benchmark/" ! -name "dummy.md" -name "*.md" -type f)
          if [[ "${files}" != "" ]]; then
            echo "${files}" | xargs -I {i} sh -c 'echo "# $(basename {i})\n"; cat {i}' > ./src/Logger/Logger.Benchmark/README.md
          fi

      - name: Download Logic.Benchmark
        uses: actions/download-artifact@v3
        with:
          name: Logic.Benchmark
          path: ./BenchmarkDotNet.Artifacts/Logic.Benchmark/
      - name: Write summary to README.md
        run: |
          files=$(find "./BenchmarkDotNet.Artifacts/Logic.Benchmark/" ! -name "dummy.md" -name "*.md" -type f)
          if [[ "${files}" != "" ]]; then
            echo "${files}" | xargs -I {i} sh -c 'echo "# $(basename {i})\n"; cat {i}' > ./src/Logic/Logic.Benchmark/README.md
          fi

      - name: Download MemoryLeak.Benchmark
        uses: actions/download-artifact@v3
        with:
          name: MemoryLeak.Benchmark
          path: ./BenchmarkDotNet.Artifacts/MemoryLeak.Benchmark/
      - name: Write summary to README.md
        run: |
          files=$(find "./BenchmarkDotNet.Artifacts/MemoryLeak.Benchmark/" ! -name "dummy.md" -name "*.md" -type f)
          if [[ "${files}" != "" ]]; then
            echo "${files}" | xargs -I {i} sh -c 'echo "# $(basename {i})\n"; cat {i}' > ./src/MemoryLeak/MemoryLeak.Benchmark/README.md
          fi

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "[auto commit] Benchmark result updated."
