name: dotnet lint

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 1 # At AM10:00 JST on Monday

jobs:
  lint_csharp:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: guitarrapc/actions/.github/workflows/reusable-dotnet-lint@main
