name: Grpc Build

on:
  workflow_dispatch:
    inputs:
      push-image:
        type: boolean
        description: "push-image: true - build and push image. false - build only."
        required: true
        default: false
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday.
  push:
    branches:
      - "main"
    paths:
      - "src/Grpc/**/*"
      - ".github/workflows/grpc-build.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - "src/Grpc/**/*"
      - ".github/workflows/grpc-build.yaml"

env:
  BUILD_CONFIG: Release
  BUILD_WASM: "false"
  DIR_NAME: Grpc
  DOCKER_BUILDKIT: "1"
  DOCKER_PUSH_ENABLED: "${{ github.event.inputs.push-image == 'true' && 'true' || (github.event_name == 'push' || github.event_name == 'schedule') }}"
  DOCKER_TAG_NAME: grpc

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        project:
          [
            "GrpcApiService",
            "GrpcAspNetCore60",
            "GrpcAspNetCore60.HealthCheckSupport",
          ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          restore-wasm-workload: ${{ env.BUILD_WASM }}
      - name: dotnet build
        run: dotnet build ./src/${{ env.DIR_NAME }}/${{ matrix.project}}/${{ matrix.project }}.csproj -c ${{ env.BUILD_CONFIG }}
      - name: dotnet test
        run: |
          if [[ "${{ matrix.project }}" == *Tests ]]; then
            dotnet test ./src/${{ env.DIR_NAME }}/${{ matrix.project}}/${{ matrix.project }}.csproj -c ${{ env.BUILD_CONFIG }}
          fi
      - name: Run benchmark
        run: |
          if [[ "${{ matrix.project }}" == *Benchmark ]]; then
            dotnet run --project ./src/${{ env.DIR_NAME }}/${{ matrix.project}}/${{ matrix.project }}.csproj -c ${{ env.BUILD_CONFIG }}
            cat ./BenchmarkDotNet.Artifacts/results/${{ matrix.project }}.Benchmarks-report-github.md >> "$GITHUB_STEP_SUMMARY"
          fi

  docker:
    strategy:
      fail-fast: false
      matrix:
        project:
          [
            "GrpcApiService",
            "GrpcAspNetCore60",
            "GrpcAspNetCore60.HealthCheckSupport",
          ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: guitarrapc/actions/.github/actions/git-shortsha@main
        id: sha
      - uses: ./.github/actions/to-lower
        id: lower
        with:
          project: ${{ matrix.project }}
      - name: docker build
        run: docker build -t "${{ steps.lower.repository }}:latest-${{ env.DOCKER_TAG_NAME }}-${{ steps.lower.project }}" -f "src/${{ env.DIR_NAME }}/${{ matrix.project }}/Dockerfile" .
      # docker push
      - if: ${{ env.DOCKER_PUSH_ENABLED == 'true' }}
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SYNCED_DOCKER_USER }}
          password: ${{ secrets.SYNCED_DOCKER_PASS }}
      - if: ${{ env.DOCKER_PUSH_ENABLED == 'true' }}
        name: docker push (latest)
        run: docker push "${{ steps.lower.repository }}:latest-${{ env.DOCKER_TAG_NAME }}-${{ steps.lower.project }}"
      - if: ${{ env.DOCKER_PUSH_ENABLED == 'true' }}
        name: docker push (tag)
        run: |
          docker tag "${{ steps.lower.repository }}:latest-${{ env.DOCKER_TAG_NAME }}-${{ steps.lower.project }}" "${{ steps.lower.repository }}:${{ steps.sha.sha-short }}-${{ env.DOCKER_TAG_NAME }}-${{ steps.lower.project }}"
          docker push "${{ steps.lower.repository }}:${{ steps.sha.sha-short }}-${{ env.DOCKER_TAG_NAME }}-${{ steps.lower.project }}"
