name: Lint Dotnet

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1 # At AM9:00 JST on Monday

jobs:
  lint:
    uses: guitarrapc/actions/.github/workflows/reusable-dotnet-lint.yaml@main
    permissions:
      contents: read
      pull-requests: write
