name: SourceGenerator Build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday.
  push:
    branches:
      - "main"
    paths:
      - "src/SourceGenerator/**/*"
      - ".github/workflows/sourcegenerator-build.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - "src/SourceGenerator/**/*"
      - ".github/workflows/sourcegenerator-build.yaml"

env:
  BUILD_CONFIG: Release
  DIR_NAME: SourceGenerator

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        project:
          [
            "SourceGeneratorBasic",
            "SourceGeneratorBasic.ConsoleApp",
            "SourceGeneratorBasic.UnitTests",
          ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
      - name: dotnet build
        run: dotnet build ./src/${{ env.DIR_NAME }}/${{ matrix.project}}/${{ matrix.project }}.csproj -c ${{ env.BUILD_CONFIG }}
      - name: dotnet test
        run: |
          if [[ "${{ matrix.project }}" == *Tests ]]; then
            dotnet test ./src/${{ env.DIR_NAME }}/${{ matrix.project}}/${{ matrix.project }}.csproj -c ${{ env.BUILD_CONFIG }}
          fi
      - name: Run benchmark
        run: |
          if [[ "${{ matrix.project }}" == *Benchmark ]]; then
            dotnet run --project ./src/${{ env.DIR_NAME }}/${{ matrix.project}}/${{ matrix.project }}.csproj -c ${{ env.BUILD_CONFIG }}
            cat ./BenchmarkDotNet.Artifacts/results/${{ matrix.project }}.Benchmarks-report-github.md >> "$GITHUB_STEP_SUMMARY"
          fi
